In [8]:
import numpy as np
import numpy.linalg as la

In [50]:
def shifted_inverse_iteration(A, sigma=0, error=1e-3):
    N = A.shape[0]
    A -= np.eye(N)*sigma
    x = np.ones((N,1))
    n, e = 0, 0
    while True:
        y = la.solve(A, x)
        e = (y.T @ x) / (x.T @ x)
        x = y/la.norm(y)
        n += 1
        if abs(1/e + sigma) % 1 < error:
            return 1/e + sigma
    
A = np.array([
    [5, 4, 4, 2, -1],
    [0, 6, -4, -1, -4],
    [0, 0, 4, -4, 4],
    [0, 0, 0, -7, 5],
    [0, 0, 0, 0, 8]
],dtype=float)

shifted_inverse_iteration(A, sigma=8.4)

array([[8.00061103]])

In [25]:
# 12.9
error = 1e-2
eigen_value = np.array([-1., 2., 4., 8., 9.])
sigma = 2.4

sorted_eigen_value = np.sort(abs(eigen_value))
# (min/min_2)**n = error -> n = log_{min/min_2}^error -> n = ln(error)/ln(min/min_2)
iter_0 = np.log(error)/np.log(sorted_eigen_value[0]/sorted_eigen_value[1])
print(int(iter_0)+1)

eigen_value -= sigma
sorted_eigen_value = np.sort(abs(eigen_value))
iter_shift = np.log(error)/np.log(sorted_eigen_value[0]/sorted_eigen_value[1])
print(int(iter_shift)+1)

7
4


In [46]:
# 12.10
eigen_value = np.array([-8., 4., 1.])
sigma = 0.5
iter = 5
u = np.array([1,0,-1])
x0 = np.array([-1,-1,-1])
e0 = la.norm(u-x0 ,ord=np.inf)

sorted_eigen_value = np.sort(abs(eigen_value))
error_0 = (sorted_eigen_value[0]/sorted_eigen_value[1])**iter
print(error_0*e0)

eigen_value -= sigma
sorted_eigen_value = np.sort(abs(eigen_value))
error_shift = (sorted_eigen_value[0]/sorted_eigen_value[1])**iter
print(error_shift*e0)

0.001953125
0.00011899803653239719


In [68]:
# 12.12
X = np.array([
    [16,8,4],
    [16,9,16],
    [18,15,10]
])
e = np.array([1.,4.,3.])
D = np.diag(e)
p = np.inf
sigma = 4.3

i1 = np.argmax(e)
i2 = np.argmin(abs(e))
i3 = np.argmin(abs(e-sigma))

V = X @ D
v1 = V[:,i1]
v1 /= la.norm(v1,p)
v2 = V[:,i2]
v2 /= la.norm(v2,p)
v3 = V[:,i3]
v3 /= la.norm(v3,p)
print(v1)
print(v2)
print(v3)

[0.53333333 0.6        1.        ]
[0.88888889 0.88888889 1.        ]
[0.53333333 0.6        1.        ]


In [73]:
# 12.13
Q1 = 0.3*(2/8)**3
Q2 = 33*1420/355
print(Q1, Q2)

0.0046875 132.0


In [15]:
# 12.14
import numpy as np
import scipy.linalg as la
def inverse_iteration(A, x_0, p=2):
    x_0 = x_0/np.linalg.norm(x_0,p)
    x_k = x_0
    while True:
        P, L, U = la.lu(A)
        # PLUx = b
        # L @ Ux = P.T @ b
        # U @ x = b'
        Ux = la.solve_triangular(L, x_k, lower=True)
        y_k = la.solve_triangular(U, Ux)
        x_k_n = y_k/np.linalg.norm(y_k,p)
        e = (y_k.T @ x_k_n) / (x_k_n.T @ x_k_n)
        if np.linalg.norm(x_k_n-x_k,2)<1e-12:
            break
        x_k = x_k_n
    return 1/e, x_k

def shifted_inverse_iteration(A, x_0, sigma=1, p=2):
    x_0 = x_0/np.linalg.norm(x_0,p)
    x_k = x_0
    A -= np.eye(A.shape[0])*sigma
    for i in range(500):
        P, L, U = la.lu(A)
        # PLUx = b
        # L @ Ux = P.T @ A
        # U @ x = b'
        Ux = la.solve_triangular(L, x_k, lower=True)
        y_k = la.solve_triangular(U, Ux)
        x_k_n = y_k/np.linalg.norm(y_k,p)
        x_k = x_k_n
    e = (y_k.T @ x_k_n) / (x_k_n.T @ x_k_n)
    return 1/e+sigma, x_k


A = np.array([
    [100, 4],
    [0, 6]
],dtype=float)
x_0 = np.array([
    [1/2**0.5],
    [1/2**0.5]
])


In [16]:
inverse_iteration(A, x_0)

(array([[6.]]),
 array([[-0.04251472],
        [ 0.99909584]]))

In [17]:
shifted_inverse_iteration(A, x_0)

(array([[6.]]),
 array([[-0.04251472],
        [ 0.99909584]]))

In [11]:
np.linalg.eig(A)

(array([100.,   6.]),
 array([[ 1.        , -0.04251472],
        [ 0.        ,  0.99909584]]))