In [114]:
import numpy as np
import numpy.linalg as la
from sympy import *
import scipy.optimize as opt
import matplotlib.pyplot as plt

In [3]:
a = -8
b = 11
i = 4

r = 0.618**i*(b-a)
r

2.7714528937439997

In [9]:
# 16.2
x = Symbol('x')
h = Symbol('h')
x0 = 1
f = 1*x**3 + 2*x**2 + 3*x +4
approx = f.subs(x,x0) + diff(f,x).subs(x,x0)*h + 0.5 * diff(f,x,2).subs(x,x0)*h**2
approx

5.0*h**2 + 10*h + 10

In [12]:
# 16.4
x0 = 0.25
x = Symbol('x')
f = -exp(-x**2)
x1 = x0 - diff(f,x).subs(x,x0)/diff(f,x,2).subs(x,x0)
x1

-0.0357142857142857

In [104]:
# 16.10
def hessian(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Hessian = A.jacobian(B).jacobian(B).subs({x:x0, y:y0})
    return np.array(Hessian).astype(np.float64)

def gradient(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Gradient = A.jacobian(B).subs({x:x0, y:y0})
    return np.array(Gradient).astype(np.float64).T

def newtons_method(f, x_init, tol):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    cnt = -1
    while(la.norm(x_prev - x_new) > tol):
        x_prev = x_new
        s = -la.solve(hessian(f, x_prev), gradient(f, x_prev))
        x_new = x_prev + s
        cnt += 1
    return x_new, cnt

In [105]:
x_init = np.array([[1],[2]])
x, y = Symbol('x'), Symbol('y')
f = 15 * x**2- 6 * x + 6 + 22*y**2- x*y
tol = 1e-7
newtons_method(f, x_init, tol)

(array([[0.20015163],
        [0.0045489 ]]),
 1)

In [83]:
# 16.11
x, y = Symbol('x'), Symbol('y')
f = 1.5*x**2 + 2*x*y + 2.5*y**2
X0 = np.array([[8], [5]])
#s0 = -la.solve(hessian(f, X0), gradient(f, X0).T)
s0 = -X0
s0

array([[-8],
       [-5]])

In [108]:
# 16.12
x, y = Symbol('x'), Symbol('y')
f = 7*x**2 + 3*x*y + 7*y**2 + 13*exp(10*x*y) + 14*sin(y)**2 + 2*cos(x*y)
x0 = np.array([[0], [1]])
print(gradient(f, x0))
print()
print(hessian(f, x0))
s1 = -la.solve(hessian(f, x0), gradient(f, x0))
x1 = x0 + s1
print(x1)
print()
print(-gradient(f, x0))

[[133.        ]
 [ 26.73016398]]

[[1312.          133.        ]
 [ 133.            2.34788858]]
[[-0.22198221]
 [ 2.18977935]]

[[-133.        ]
 [ -26.73016398]]


In [107]:
# 16.13
x, y = Symbol('x'), Symbol('y')
f = 3 + x**2/8 + y**2/8 - sin(x)*cos(sqrt(2)/2*y)
x0 = np.array([[pi/3], [pi/2/sqrt(2)]]).astype(np.float64)
alpha = 1.581
print(gradient(f, x0))
print()
print(hessian(f, x0))
s1 = -la.solve(hessian(f, x0), gradient(f, x0))
x1 = x0 + s1
print(x1)
print()
s2 = -gradient(f, x0)
x2 = x0 + alpha * s2
print(x2)

[[-0.091754  ]
 [ 0.71069289]]

[[0.86237244 0.25      ]
 [0.25       0.55618622]]
[[ 1.59546844]
 [-0.41351805]]

[[ 1.19226063]
 [-0.01288472]]


In [ ]:
# 16.14
import numpy as np
import matplotlib.pyplot as plt

brackets = []
gs = (np.sqrt(5) - 1) / 2
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)

# Begin your modifications below here
f1, f2 = f(m1), f(m2)
while b - a > 1e-5:
    if f1>= f2:
        a = m1
    else:
        b = m2
    m1 = a + (1 - gs) * (b - a)
    m2 = a + gs * (b - a)    
    if f1>= f2:
        f1 = f2
        f2 = f(m2)
    else:
        f2 = f1
        f1 = f(m1)
    
    brackets.append([a, m1, m2, b])

# End your modifications above here

# Plotting code below, no need to modify
x = np.linspace(-10, 10)
plt.plot(x, f(x))

brackets = np.array(brackets)
names=['a', 'm1', 'm2', 'b']
for i in range(4):
    plt.plot(brackets[:, i], 3*np.arange(len(brackets)), 'o-', label=names[i])
plt.legend()

In [115]:
def func(r):
    x, y = r
    return 3 +((x**2)/8) + ((y**2)/8) - np.sin(x)*np.cos((2**-0.5)*y)

def obj_func(alpha, x, s):
    # code for computing the objective function at (x+alpha*s)
    return func(x + alpha * s)

def steepest_descent(f, x_init, tol):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev - x_new, 2) > tol):
        x_prev = x_new
        s = -gradient(f, x_prev)
        alpha = opt.minimize_scalar(obj_func, args=(x_prev, s)).x
        x_new = x_prev + alpha*s

    return x_new

In [117]:
x, y = Symbol('x'), Symbol('y')
f = 3 + x**2/8 + y**2/8 - sin(x)*cos(sqrt(2)/2*y)
x_init = np.array([[pi/3], [pi/2/sqrt(2)]]).astype(np.float64)
steepest_descent(f, x_init, 1e-6)

array([[1.25235323e+00],
       [1.29174860e-08]])

In [122]:
def func(r):
    x, y = r
    return np.float64(3 +((x**2)/8) + ((y**2)/8) - np.sin(x)*np.cos((2**-0.5)*y))

def obj_func(alpha, x, s):
    # code for computing the objective function at (x+alpha*s)
    return func(x + alpha * s)
r = np.array([[pi/3], [pi/2/sqrt(2)]]).astype(np.float64)
x, y = r
x, y



2.6789179719752454

In [ ]:
# 16.16
import numpy as np
from sympy import *

# complete the function below
def dfunc(x):
    # Add your code here
    y = Symbol('y')
    f = -exp(-y**2) * (y + sin(y))
    return diff(f,y).subs(y,x)
    

# complete the function below
def d2func(x):
    # Add your code here
    y = Symbol('y')
    f = -exp(-y**2) * (y + sin(y))
    return diff(f,y,2).subs(y,x)

# run Newton's Method
newton_list = [x0]
x = x0
while abs(dfunc(x)) > tol:
    x -= dfunc(x)/d2func(x)
    newton_list.append(x)
newton_guesses = np.array(newton_list).astype(np.float64)