In [2]:
import numpy as np
import numpy.linalg as la

In [3]:
# 18a.5
A = np.array([[2.05650, 4.33830, -2.44230], [-1.74620, 4.06100, 4.43900], [5.80360, 0.67640, 2.77910]])
X = np.array([[-0.63000, 0.77000, 0.11000], [-0.61000, -0.40000, -0.69000], [-0.49000, -0.50000, 0.72000]])
D = np.array([[49,  0,  0], [ 0, 36,  0], [ 0,  0, 25]])

In [4]:
V = X
print(V)
Sigma = np.sqrt(D)
print(Sigma)
Sigma
print(A @ V)
U =  A @ V @ la.inv(Sigma)
print(U)

[[-0.63  0.77  0.11]
 [-0.61 -0.4  -0.69]
 [-0.49 -0.5   0.72]]
[[7. 0. 0.]
 [0. 6. 0.]
 [0. 0. 5.]]
[[-2.745231  1.069335 -4.525668]
 [-3.552214 -5.188474  0.201908]
 [-5.430631  2.808662  2.172632]]
[[-0.39217586  0.1782225  -0.9051336 ]
 [-0.50745914 -0.86474567  0.0403816 ]
 [-0.77580443  0.46811033  0.4345264 ]]


In [9]:
# 18a.6
AV = np.array([[-0.863, 4.405, 1.383, 0.092], [-5.991, -0.324, 0.149, -0.656], [-3.909, 1.237, -2.031, 0.496], [-3.441, -2.009, 1.702, 0.561]])
X = np.array([[-0.870, 0.450, 0.130, -0.140], [-0.170, -0.600, 0.100, -0.780], [-0.450, -0.580, -0.480, 0.480], [-0.100, -0.320, 0.860, 0.380]])
D = np.array([[64,  0,  0,  0], [ 0, 25,  0,  0], [ 0,  0,  9,  0], [ 0,  0,  0,  1]])

In [10]:
Sigma = np.sqrt(D)
U = AV @ la.inv(Sigma)
U

array([[-0.107875  ,  0.881     ,  0.461     ,  0.092     ],
       [-0.748875  , -0.0648    ,  0.04966667, -0.656     ],
       [-0.488625  ,  0.2474    , -0.677     ,  0.496     ],
       [-0.430125  , -0.4018    ,  0.56733333,  0.561     ]])

In [15]:
# 18a.7
np.sort(np.power([5,3,4],2))[::-1]

array([25, 16,  9], dtype=int32)

In [17]:
# 18a.8
np.sort(np.sqrt([10,6,4]))[::-1]

array([3.16227766, 2.44948974, 2.        ])

In [ ]:
# 18a.9
import numpy as np

V = X
Vtransp = V.T
Sigma = np.sqrt(s)
U = A @ V @ np.linalg.inv(np.diag(Sigma))

In [ ]:
# 18a.10
x = left_multiply_with_V(right_multiply_with_U(b)/sigma)