In [1]:
import numpy as np
import numpy.linalg as la

In [5]:
U = np.array([[-0.56, 0.01, -0.80, 0.19],
              [-0.51, -0.41, 0.17, -0.74],
              [-0.03, -0.84, 0.13, 0.52],
              [-0.65, 0.35, 0.56, 0.38]])
Sigma = np.diag([8, 6, 0, 0])
VT = np.array([[-0.61, -0.47, -0.60, -0.23],
               [0.06, -0.09, -0.34, 0.93],
               [0.76, -0.12, -0.58, -0.27],
               [-0.22, 0.87, -0.44, -0.07]])
A_pinv = VT.T @ la.pinv(Sigma) @ U.T
A_pinv

array([[ 0.0428    ,  0.0347875 , -0.0061125 ,  0.0530625 ],
       [ 0.03275   ,  0.0361125 ,  0.0143625 ,  0.0329375 ],
       [ 0.04143333,  0.06148333,  0.04985   ,  0.02891667],
       [ 0.01765   , -0.0488875 , -0.1293375 ,  0.0729375 ]])

In [34]:
# 18b.4
U = np.array([[-0.58, 0.73, 0.20, -0.29], [-0.50, -0.66, 0.25, -0.51], [-0.64, -0.15, -0.39, 0.64], [-0.01, -0.05, 0.87, 0.50]])
sigma = np.array([[6.00, 0.00, 0.00], [0.00, 4.00, 0.00], [0.00, 0.00, 1.00], [0.00, 0.00, 0.00]])
Vt = np.array([[-0.44, -0.81, -0.40], [0.76, -0.57, 0.31], [-0.48, -0.17, 0.86]])
sigmaV = (sigma@Vt)
print(sigmaV)
A_1 = np.outer(U[:,0], sigmaV[0])
print(repr(A_1))
A_2 = A_1 + np.outer(U[:, 1], sigmaV[1])
print(repr(A_2))

[[-2.64 -4.86 -2.4 ]
 [ 3.04 -2.28  1.24]
 [-0.48 -0.17  0.86]
 [ 0.    0.    0.  ]]
array([[1.5312, 2.8188, 1.392 ],
       [1.32  , 2.43  , 1.2   ],
       [1.6896, 3.1104, 1.536 ],
       [0.0264, 0.0486, 0.024 ]])
array([[ 3.7504,  1.1544,  2.2972],
       [-0.6864,  3.9348,  0.3816],
       [ 1.2336,  3.4524,  1.35  ],
       [-0.1256,  0.1626, -0.038 ]])


In [35]:
# 18b.9
def solve_SVD(U, sigma, V, b):
    y = la.solve(sigma, U.T @ b)
    x = V @ y
    return x

In [37]:
U = np.array([[0, 1/np.sqrt(2), 1/np.sqrt(2)],
              [0, 1/np.sqrt(2), -1/np.sqrt(2)],
              [1, 0, 0]])
sigma = np.diag([7, 4, 1])
V = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
b = np.array([np.sqrt(2), np.sqrt(2), 1])
solve_SVD(U, sigma, V, b)

array([2.02930727e-17, 5.00000000e-01, 1.42857143e-01])

In [45]:
# 18b.10
a = 87
b = 46
k = 2

(a*b-(a*k +k+ k * b))*64

238976

In [ ]:
# 18b.11
import numpy as np

print(U.shape, sigmavec.shape, V.shape)

sigma_plus = np.zeros((V.shape[0], U.shape[0]))
for i in range(len(sigmavec)):
    sigma_plus[i][i] = 1/sigmavec[i]
A_plus = V @ sigma_plus @ U.T

In [ ]:
# 18b.12
import numpy as np

sigmaV = sigma@V.T
A_k = 0
for i in range(k):
    A_k += np.outer(U[:,i], sigmaV[i])

In [ ]:
# 18b.13
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la

u, s, vt = la.svd(image, full_matrices = False)
# plt.plot(np.arange(50), s[:50])
# plt.xlabel('number')
# plt.ylabel('singular values')
# plt.title('xxx')

lower_bound = f*np.sum(s)
k = 0
for i in range(len(s)):
    if np.sum(s[:i])>lower_bound:
        k = i
        break

image_compressed = 0
sV = np.diag(s)@vt
for i in range(k):
    image_compressed += np.outer(u[:,i], sV[i])

plt.imshow(image_compressed, cmap = 'gray')