In [1]:
# 9.10 Investigating Power Usage
test_data = {'Test0': [('Converter', 0.5163042450382166), 
                       ('FPU', 0.1952165856525374), 
                       ('LED0', 0.755318251706514), 
                       ('Buzzer', 0.7262554929246308), 
                       ('Microchip0', 0.36964927437379713), 
                       ('LED1', 0.8482800866574957), 
                       ('Microchip1', 0.7682351569255519), 
                       ('Speaker', 0.4545615815003953), 
                       ('Screen', 0.7720582898501619), 
                       ('Microphone', 0.5825388822468633), 
                       ('EnergyConsumed', 2.1644731604368777)], 
             'Test1': [('EnergyConsumed', 2.7811021920887544), 
                       ('LED1', 0.9226696724326391), 
                       ('FPU', 0.8622345364446008), 
                       ('LED0', 0.9326035195539446), 
                       ('Speaker', 0.19491952556338699), 
                       ('Microchip0', 0.6196267225024642), 
                       ('Buzzer', 0.2228554856257121), 
                       ('Microphone', 0.8103034088017103), 
                       ('Screen', 0.8641105491993878), 
                       ('Converter', 0.8388995082466822), 
                       ('Microchip1', 0.4293640997613105)], 
             'Test2': [('Speaker', 0.6243578325081433), 
                       ('Microchip1', 0.28751795122694124), 
                       ('LED0', 0.2633953306828657), 
                       ('Converter', 0.8425077583930315), 
                       ('FPU', 0.5909923442630695), 
                       ('EnergyConsumed', 2.393215878043478), 
                       ('Microphone', 0.3671301226534198), 
                       ('Buzzer', 0.3282180973717467), 
                       ('Microchip0', 0.9304882590484549),
                       ('Screen', 0.41110999657137026), 
                       ('LED1', 0.5283511728103246)], 
             'Test3': [('EnergyConsumed', 1.6850883882594467), 
                       ('LED0', 0.5679321655544027), 
                       ('LED1', 0.40561317714064404), 
                       ('Screen', 0.18931778453601844), 
                       ('Converter', 0.6481610767947171), 
                       ('FPU', 0.2878630921453941), 
                       ('Buzzer', 0.21923276178413964), 
                       ('Microphone', 0.8092421770433739), 
                       ('Microchip1', 0.4440767786694866), 
                       ('Speaker', 0.5588971045139619), 
                       ('Microchip0', 0.4645923188831328)], 
             'Test4': [('LED0', 0.15937531151582696), 
                       ('Microchip0', 0.33929539571291345), 
                       ('Screen', 0.5509434895204425), 
                       ('FPU', 0.20490038224856288), 
                       ('EnergyConsumed', 2.3384798693236055), 
                       ('Speaker', 0.825948831788622), 
                       ('LED1', 0.8677562067834346), 
                       ('Buzzer', 0.9698947082284981), 
                       ('Microchip1', 0.8687839952425894), 
                       ('Microphone', 0.371467243049323), 
                       ('Converter', 0.9324323704475799)], 
             'Test5': [('LED1', 0.646609256707085), 
                       ('FPU', 0.7504353917785044), 
                       ('LED0', 0.18547962170270837), 
                       ('Microphone', 0.80721801579766), 
                       ('Buzzer', 0.6269994366668834), 
                       ('EnergyConsumed', 2.081093402949808), 
                       ('Microchip0', 0.6034876798074444), 
                       ('Microchip1', 0.9243029419463998), 
                       ('Speaker', 0.3292064298098809), 
                       ('Screen', 0.5266090492286143), 
                       ('Converter', 0.04295779698232394)], 
             'Test6': [('Speaker', 0.2706374578545422), 
                       ('Microchip1', 0.08376134058310536), 
                       ('Buzzer', 0.598481654262197), 
                       ('LED0', 0.05352667735922789), 
                       ('Microchip0', 0.7351200948878517), 
                       ('Microphone', 0.35874795705942153), 
                       ('EnergyConsumed', 1.702247220115344), 
                       ('Converter', 0.10260086002604807), 
                       ('Screen', 0.25369244739851926),
                       ('FPU', 0.9868508127788752), 
                       ('LED1', 0.1276777265588226)], 
             'Test7': [('Microchip1', 0.4257771871419288), 
                       ('Speaker', 0.48543892417738754), 
                       ('FPU', 0.3102496210756239), 
                       ('LED0', 0.8468605660645405), 
                       ('Buzzer', 0.7800609464647525), 
                       ('Screen', 0.49334785574199946), 
                       ('EnergyConsumed', 1.9573865161203976), 
                       ('Converter', 0.5467553060284945), 
                       ('Microchip0', 0.8097238841965849), 
                       ('LED1', 0.2519720710112262), 
                       ('Microphone', 0.18862349374582166)], 
             'Test8': [('Converter', 0.23455845510235107), 
                       ('LED0', 0.02941279544505615), 
                       ('Speaker', 0.872065751406134), 
                       ('Screen', 0.373562171706165), 
                       ('Microchip0', 0.4345843018095452), 
                       ('Microphone', 0.5548144698472421), 
                       ('FPU', 0.5985117827996481), 
                       ('LED1', 0.5155634598069427),
                       ('Microchip1', 0.5678507419364831), 
                       ('EnergyConsumed', 2.1625846183353064), 
                       ('Buzzer', 0.3832163421639927)],
             'Test9': [('Screen', 0.4581588975892441),
                       ('Microphone', 0.4142219168452328), 
                       ('EnergyConsumed', 1.6726469787024407),
                       ('Buzzer', 0.5186733576720471), 
                       ('LED0', 0.7869466148607759),
                       ('Converter', 0.4024270308942175), 
                       ('LED1', 0.017213017772173655), 
                       ('FPU', 0.1501166401407129),
                       ('Microchip0', 0.4763043232199772),
                       ('Speaker', 0.6543243802276577), 
                       ('Microchip1', 0.48591544946796406)]}

components = ['Microphone', 'Screen', 'FPU', 'LED0', 'LED1', 'Converter', 'Speaker', 'Buzzer', 'Microchip0', 'Microchip1']

In [16]:
import numpy as np
A = np.array([[dict(test_data[test])[component] for component in components] for test in test_data.keys()])
b = np.array([dict(test_data[test])['EnergyConsumed'] for test in test_data.keys()])
power_usage = np.linalg.inv(A) @ b

array([0.09999873, 0.86960675, 0.75879667, 0.1558893 , 0.40435902,
       0.32214279, 0.89396874, 0.01810064, 0.46769574, 0.08751339])

In [24]:
# 9.11 Predict Popularity
import numpy as np

print(n,m,k)

for i in range(n):
    print(get_friend_prefs(i))

for j in range(k):
    print(get_movie_attr(j))


5 8 11
[9 5 6 5 5 8 4 5]
[2 2 4 3 4 7 3 6]
[2 5 4 5 3 3 4 6]
[6 2 3 3 5 8 5 4]
[7 6 1 5 4 6 8 7]
[0.04823279 0.18918532 0.04491418 0.19958797 0.10611783 0.13291451
 0.16640995 0.11263745]
[0.23879017 0.08878604 0.21963288 0.01115152 0.02879214 0.15914316
 0.14169652 0.11200757]
[0.01857663 0.18986481 0.10672712 0.17612164 0.2380835  0.13109239
 0.12199365 0.01754026]
[0.20223106 0.22425282 0.20125053 0.12291264 0.05388518 0.00263924
 0.09966938 0.09315915]
[0.00478263 0.2313713  0.22855852 0.06169731 0.06551523 0.10075865
 0.19293821 0.11437816]
[0.2000094  0.00538114 0.16430988 0.19417063 0.12926672 0.05829151
 0.05135923 0.19721149]
[0.06452767 0.00697118 0.16580941 0.25949063 0.15041219 0.17375899
 0.0045749  0.17445503]
[0.04331968 0.20795359 0.07399139 0.1499805  0.00409556 0.25816745
 0.25310042 0.0093914 ]
[0.13848247 0.04229805 0.1467761  0.17196724 0.17318733 0.08074396
 0.10844984 0.13809502]
[0.12052165 0.18131012 0.20411857 0.00188704 0.07263424 0.22456168
 0.1203278  0.0746389 ]
[0.29685067 0.06256394 0.01901204 0.12643814 0.09631391 0.18535302
 0.10698674 0.10648154]

In [ ]:
pref = np.array([get_friend_prefs(i) for i in range(n)]) # n x m
attr = np.array([get_movie_attr(j) for j in range(k)]) # k x m
score = pref @ attr.T / m # n x k
ratings = np.sum(score, axis=0)
top = np.argmax(ratings)