In [53]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as sla

<img src = 'Quiz3/1.png'>

In [2]:
# LU Solve Time Complexity
N_M = 700
t1 = 11
t2 = 3

N_A = 2800
b = 20
t_factorization = N_A**3/N_M**3 * t1
t_solve = N_A ** 2 / N_M **2 * t2 *b
t = t_factorization + t_solve
t

1664.0

<img src = 'Quiz3/2.jpg'>

In [61]:
# Estimate Error from Monte Carlo

def check(xy):
    x = xy[0]
    y = xy[1]
    n = 1.5
    c = 1
    if np.cbrt((x-n) ** 2) + (1 - (x - n)**2)**0.5 + c >= y and np.cbrt((x-n) ** 2) - (1 - (x - n)**2)**0.5 + c <= y:
        return 1
    else:
        return 0


x = 3
y = 3
sample = [(1.5, 0.5), (2.0, 1.0), (1.5, 1.5), (1.0, 0.5), (2.0, 1.5), (2.5, 1.5)]
n_in = sum([check(i) for i in sample])
area = n_in / len(sample) * x * y
abs_error = abs(area - np.pi)
rel_error = abs_error / np.pi
print("abs_error:" + str(abs_error), "rel_error" + str(rel_error))

abs_error:2.858407346410207 rel_error0.9098593171027441


<img src = 'Quiz3/3.jpg'>

In [35]:
array = np.array([ [0, 13, 0, 5, -13, 0, 0],
                   [0, 2, 0, -6, 4, 0, 7],
                   [-14, 0, 0, 0, 0, 0, 14],
                   [0, 0, 0, 0, 0, -6, 0],
                   [0, 0, 0, -10, -9, 0, 0],
                   [-12, -3, -11, 0, 0, 14, 0],
                   [-15, 0, -6, 0, 0, -12, -9]])
la.norm(array,1)
# np.max(np.sum(np.abs(array), axis = 0)) 

41

<img src = 'Quiz3/4.jpg'>


Entry with largest abs_value in the first column

<img src = 'Quiz3/5.jpg'>

In [67]:
n = 5000
error = 1e-2
objective_error = 1e-6
(error * np.sqrt(n) / objective_error)**2

500000000000.0001

<img src = 'Quiz3/6.jpg'>

<img src = 'Quiz3/7.jpg'>

In [69]:
A = np.array([[4, 1],[12,12]])

def lu_decomp(A):
    """(L, U) = lu_decomp(A) is the LU decomposition A = L U
       A is any matrix
       L will be a lower-triangular matrix with 1 on the diagonal, the same shape as A
       U will be an upper-triangular matrix, the same shape as A
    """
    n = A.shape[0]
    if n == 1:
        L = np.array([[1]])
        U = A.copy()
        return (L, U)

    A11 = A[0,0]
    A12 = A[0,1:]
    A21 = A[1:,0]
    A22 = A[1:,1:]

    L11 = 1
    U11 = A11

    L12 = np.zeros(n-1)
    U12 = A12.copy()

    L21 = A21.copy() / U11
    U21 = np.zeros(n-1)

    S22 = A22 - np.outer(L21, U12)
    (L22, U22) = lu_decomp(S22)

    L = np.block([[L11, L12], [L21, L22]])
    U = np.block([[U11, U12], [U21, U22]])
    return (L, U)
lu_decomp(A)


(array([[1., 0.],
        [3., 1.]]),
 array([[4., 1.],
        [0., 9.]]))

<img src = 'Quiz3/8.jpg'>

In [ ]:
import numpy as np
import numpy.linalg as la

relErr = la.norm(x1-x2,p) / la.norm(x1,p)

<img src = 'Quiz3/9.jpg'>

In [59]:
def genRandomVect():
    # define return numpy array
    integer_range = [i for i in range(100)]
    x = list()
    for i in range(50):
        a = np.random.choice(integer_range)
        x.append(a)
        integer_range.remove(a)
    return np.array(x)
genRandomVect().shape

(50,)

In [62]:
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i]
        for j in range(i):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x

def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x

def lu_solve(L, U, b):
    """x = lu_solve(L, U, b) is the solution to L U x = b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same size as L
       b must be a vector of the same leading dimension as L
    """
    y = forward_sub(L, b)
    x = back_sub(U, y)
    return x

In [66]:
L = np.array([[1, 0, 0],
            [0, 1, 0],
            [1, 0, 1]])
U = np.array([[1, 1, 1],
            [0, 2, -6],
            [0, 0, -4]])
b = np.array([5, 2, 0])
x = lu_solve(L, U, b)
x

array([-1.  ,  4.75,  1.25])

In [99]:
import numpy as np
n = 100000
V = 6 * 6 * 2
x = 6 * np.random.rand(n) - 3
y = 6 * np.random.rand(n) - 3
z = 2 * np.random.rand(n)

def check_in(x, y, z):
    if abs(x) + abs(y) < 3 and z > 0 and z < f(x,y):
        return 1
    return 0

n_in = np.sum(np.array([check_in(x[i], y[i], z[i]) for i in range(n)]))
volume = V * n_in/n

array([-0.248757  ,  2.88472812, -2.48550598, -1.26783462,  1.62932789,
       -2.38658379, -2.96965764, -0.6040536 ,  0.93694768, -1.46779776])