In [1]:
import numpy as np

In [4]:
a = "012345678"
b = a
b += "910"
print(a)

a = (0, 1, 2, 3, 4, 5, 6, 7, 8)
b = a
b += (9,10)
print(a)
print(b)

012345678
(0, 1, 2, 3, 4, 5, 6, 7, 8)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [2]:
A = np.array([[-3, -1, -1],
              [0, -3, 2], 
              [0, -1, -6]])
eigen = np.linalg.eig(A)
print(A)
print(eigen)

[[-3 -1 -1]
 [ 0 -3  2]
 [ 0 -1 -6]]
(array([-3., -4., -5.]), array([[ 1.00000000e+00,  4.08248290e-01,  8.77708367e-18],
       [ 0.00000000e+00,  8.16496581e-01, -7.07106781e-01],
       [ 0.00000000e+00, -4.08248290e-01,  7.07106781e-01]]))


In [15]:
6912/4/12

144.0

In [17]:
relative_error = 0.48
estimated_time = 12
true_value = 1 /(1- relative_error)*estimated_time
print(true_value)

23.076923076923073


In [18]:
A = [2, 3, 4, 5, 6, 7, 8, 9]
A.pop(3)
print(A)

[2, 3, 4, 6, 7, 8, 9]


In [15]:
phi = 1.6180339887
phi_est = np.array([1.61800, 1.61810, 1.618090, 1.618050, 1.618080])
np.set_printoptions(formatter={'float': '{: 0.11f}'.format})
print(abs(phi_est - phi))

[ 0.00003398870  0.00006601130  0.00005601130  0.00001601130
  0.00004601130]


In [33]:
def comparator(A, B):
    ind = []
    for i in range(len(A)):
        if type(A[i]) == type(B[i]):
            if A[i] < B[i]:
                ind.append(i)
    return ind

In [34]:
A = [10, 'four', 'ten', 'eight']
B = [7, 'eight', 10, 'one']
ind = comparator(A,B)
print(ind)

[3]


In [39]:
def square(a):
    return a ** 2
A = np.array([1,3,5,6,7])
print(square(A))
print(np.e)
k = 5
print([i for i in range(k, 0, -1)])

[ 1  9 25 36 49]
2.718281828459045
[5, 4, 3, 2, 1]


In [91]:
k = 10
If = np.zeros(k) # Initialize the If and Ib
Ib = np.zeros(k)
#I = func_int(k)  # Get the true value of I by func_int()
I_0 = 1 - 1 / np.e
If[0] = 1 - 1 * I_0
for i in range(1, k):
    If[i] = 1 - (i + 1) * If[i - 1]
for i in range(k - 1, 0, -1):
    Ib[i - 1] = (1 -Ib[i]) / (i + 1)
print(If) 
print(Ib)
print(1- I_0)
print()
print(np.array([i for i in range(k - 1, 0, -1)]))

[ 0.36787944117  0.26424111766  0.20727664703  0.17089341189
  0.14553294057  0.12680235656  0.11238350407  0.10093196745
  0.09161229299  0.08387707006]
[ 0.36787946429  0.26424107143  0.20727678571  0.17089285714
  0.14553571429  0.12678571429  0.11250000000  0.10000000000
  0.10000000000  0.00000000000]
0.36787944117144233

[9 8 7 6 5 4 3 2 1]


In [60]:
a = [i for i in range(19, 0, -1)]
print(len(a))

19


In [73]:
A = 10.89
B = 5
C = 3
D = C + A
E = B - 6
print(type(A))
print(type(B))
print(type(D))
print(type(E))

<class 'float'>
<class 'int'>
<class 'float'>
<class 'int'>


In [74]:
8/1.07

7.4766355140186915

In [76]:
A = [12, 17, -5, 2, -3, 1, 16, 5, 18, 15]
A.index(16, 2)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
nums = np.arange(9)
A = nums[::-2]
print(A)
print(nums)

[8 6 4 2 0]
[0 1 2 3 4 5 6 7 8]


In [83]:
nums = np.arange(10)
A = np.zeros(5, dtype = int)
for i in range(10, 1, 2):
    A[i] = nums[i]
print(A)
print([i for i in range(10, 1, -2)])

[0 0 0 0 0]
[10, 8, 6, 4, 2]


In [86]:
nums = np.arange(0, 10, 2)
A = nums[::-1]
print(A)
print(np.arange(8,0, -2))

[8 6 4 2 0]
[8 6 4 2]


In [90]:
nums = np.arange(8,0, -2)
print(nums)
for i in nums:
    print(i)

[8 6 4 2]
8
6
4
2


In [2]:
python_list = [10, 20, 30, 40, 50, 50]
np_array = np.array(python_list)

In [8]:
result = np.zeros(6)
for i in range(6):
    result[i] = np_array[i] /2
print(result)

[ 5. 10. 15. 20. 25. 25.]


In [10]:
result= []
for i in range(6):
    result.append(python_list[i] /2)
print(result)

[5.0, 10.0, 15.0, 20.0, 25.0, 25.0]


In [7]:
result = np_array / 2
print(result)

[ 5. 10. 15. 20. 25. 25.]


In [11]:
7/1.06

6.60377358490566

In [13]:
a = [i for i in range(10,26)]
a[-5:]

[21, 22, 23, 24, 25]

In [14]:
a = 1.6180339887
a1 = 1.61800
a2 = 1.61810
a3 = 1.618090
a4 = 1.618050
a5 = 1.618080
A = np.array([a1, a2, a3, a4, a5])
A - a

array([-3.39887e-05,  6.60113e-05,  5.60113e-05,  1.60113e-05,
        4.60113e-05])

In [16]:
(0.004/0.01)**6*0.09

0.0003686400000000001

In [25]:
0.2872/0.01
(7/4)**6

28.722900390625

In [26]:
36/4*(3+2)*4+2

182.0

In [33]:
nums = np.arange(9)
A = np.zeros(5, dtype = int)
for i in range(5):
    A[i] = nums[i]
print(A)
nums[::-2]
np.arange(8,0,-2)    

[0 1 2 3 4]


array([8, 6, 4, 2])

In [34]:
i = 0
while i < 3:
    print(i)
    i += 1
    print(i+1)

0
2
1
3
2
4


In [35]:
0.5/0.94

0.5319148936170213

In [77]:
from random import shuffle, choice

# Sample data
names = ["Li", "Fatima", "Jaime", "Jamila", "Vincentius", "Nike", "Jean", "Sheila"]
unpermitted_pairs = [{"Li", "Sheila"},{"Fatima", "Jaime"},{"Jamila", "Vincentius"}]


def assign_pairs(names, unpermitted_pairs):
    # write some code here
    result_dict = dict()
    gifters = names.copy()
    recipients = names.copy()
    while len(gifters) > 0:
        gifter = choice(gifters)
        recipient = choice(recipients)
        while {gifter, recipient} in unpermitted_pairs or len({gifter, recipient}) == 1:
            recipient = choice(recipients)
        result_dict.update({gifter: recipient})
        gifters.remove(gifter)
        recipients.remove(recipient)
    return result_dict


            



In [78]:
names = ["Li", "Fatima", "Jaime", "Jamila", "Vincentius", "Nike", "Jean", "Sheila"]
unpermitted_pairs = [{"Li", "Sheila"},{"Fatima", "Jaime"},{"Jamila", "Vincentius"}]
result_dict = assign_pairs(names, unpermitted_pairs)
print(result_dict)

{'Sheila': 'Jean', 'Jamila': 'Jaime', 'Vincentius': 'Fatima', 'Jaime': 'Sheila', 'Fatima': 'Jamila', 'Nike': 'Li', 'Jean': 'Nike', 'Li': 'Vincentius'}
