In [1]:
import numpy as np
import numpy.linalg as la

Number of Nonzero singular value
<img src = 'Quiz6/1.jpg'>

Singular value decomposition
<img src = 'Quiz6/2.jpg'>

<img src = 'Quiz6/3.jpg'>

In [6]:
# Error of low-rank approximation
sigma = np.array([[8.00, 0.00, 0.00, 0.00], 
                  [0.00, 5.00, 0.00, 0.00], 
                  [0.00, 0.00, 4.00, 0.00], 
                  [0.00, 0.00, 0.00, 2.00],
                  [0.00, 0.00, 0.00, 0.00],
                  [0.00, 0.00, 0.00, 0.00]])
r = 3
sigma[r][r]

2.0

<img src = Quiz6/4.jpg>

In [7]:
# Maximum coefficient count for unique solution
x = np.array([5.5, 10.5, 6.5, 11.5, 9.5, 11.0, 9.5, 6.5])
len(np.unique(x))

6

In [15]:
x = np.array([11.0, 11, 7, 7, 8, 11])
len(np.unique(x))

3

<img src= Quiz6/5.jpg>

In [8]:
# Least-squares minimum norm solution
U = np.array([[0, 0, 1, 0],
              [0, 0, 0, 0],
              [1, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 1, 0, 0]])
Sigma = np.array([[9, 0, 0, 0],
                  [0, 8, 0, 0],
                  [0, 0, 4, 0],
                  [0, 0, 0, 0]])
VT = np.array([[0.00, 0.42, 0.00, 0.91],
               [0.00, 0.91, 0.00, -0.42],
               [0.36, 0.00, 0.93, 0.00],
               [0.93, 0.00, -0.36, 0.00]])
b = np.array([4, 2, 3, 1, 6])

Sigma_p = 1 / Sigma.T
Sigma_p[Sigma_p == np.inf] = 0
x = VT.T @ Sigma_p @ U.T @ b
x

<ipython-input-8-4a52f90376ff>:16: RuntimeWarning: divide by zero encountered in true_divide
  Sigma_p = 1 / Sigma.T


array([ 0.36      ,  0.8225    ,  0.93      , -0.01166667])

In [17]:
U = np.array([[0, 0, 0, 0],
              [0, 0, 1, 0],
              [1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1]])
Sigma = np.array([[8, 0, 0, 0],
                  [0, 7, 0, 0],
                  [0, 0, 4, 0],
                  [0, 0, 0, 0]])
VT = np.array([[0.00, 0.90, 0.43, 0.00],
               [0.00, -0.43, 0.90, 0.00],
               [0.32, 0.00, 0.00, 0.95],
               [-0.95, 0.00, 0.00, 0.32]])
b = np.array([2, 5, 1, 7, 5])

Sigma_p = 1 / Sigma.T
Sigma_p[Sigma_p == np.inf] = 0
x = VT.T @ Sigma_p @ U.T @ b
x

<ipython-input-17-926ae8c70e32>:16: RuntimeWarning: divide by zero encountered in true_divide
  Sigma_p = 1 / Sigma.T


array([ 0.4    , -0.3175 ,  0.95375,  1.1875 ])

<img src = Quiz6/6.jpg>

In [9]:
# Determine the norm-2
sigma = np.array([16, 10, 8, 3])
sigma.max()

16

<img src = Quiz6/7.jpg>

In [34]:
# Find RHS of normal equation / Find LHS of normal equation
t = np.array([2, 4, 7])
b = np.array([-2, 2, 6])
A = np.vstack([t**2, np.cos(t)]).T

n = A.T @ b
M = A.T @ A
print('n', repr(n))
print('M', repr(M))

n array([318.        ,   4.04841996])
M array([[2.67300000e+03, 2.48183252e+01],
       [2.48183252e+01, 1.16879678e+00]])


In [35]:
t = np.array([2, 4, 6])
b = np.array([0.74, 0.79, 1])
A = np.vstack([np.sqrt(t), np.sin(t)]).T

n = A.T @ b
M = A.T @ A
print('n', repr(n))
print('M', repr(M))

n array([ 5.07600778, -0.20440937])
M array([[12.        , -0.91208963],
       [-0.91208963,  1.47764485]])


<img src = Quiz6/8.jpg>

In [ ]:
# Estimate sales
import numpy as np
import numpy.linalg as la

A = np.vstack([given_year, np.ones(len(given_year))]).T
c1, c0 = la.lstsq(A, given_sales)[0]

pred_sales = np.vstack([pred_year, np.ones(len(pred_year))]).T @ np.array([c1, c0])

<img src = Quiz6/9.jpg>

In [ ]:
# Solve linear system using SVD
x = left_multiply_with_V(right_multiply_with_U(b)/sigma)

<img src = Quiz6/10.jpg>

In [ ]:
import numpy as np
import numpy.linalg as la

A = np.vstack([(study_time+2)**2.5, np.exp(study_time+1), study_time, np.ones(len(study_time))]).T
coeffs = la.lstsq(A, scores)[0]

Pseudoinverse conditions
<img src = Quiz6/11.jpg>
<img src = Quiz6/17.jpg>


<img src = Quiz6/12.jpg>

In [16]:
# Quadratic Fit
t = np.array([-3.0, 1.8, -4.9])
y = np.array([3.3, 7.9, 15])
A = np.vstack([t, t**2]).T
coeffs = la.lstsq(A, y)[0]
coeffs

<ipython-input-16-502a3a655ec7>:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coeffs = la.lstsq(A, y)[0]


array([2.31800073, 1.10366545])

<img src = Quiz6/13.jpg>

In [20]:
# Mixed application SVD
sigma = np.array([8, 6])
(1/sigma).max()

0.16666666666666666

<img src = Quiz6/14.jpg>

In [ ]:
# Modeling rabbit population
import numpy as np
import numpy.linalg as la

day = np.arange(len(population))
A = np.vstack([np.ones(len(day)), day]).T
coeff = la.lstsq(A, np.log(population))[0]
c0 = np.exp(coeff[0])
c1 = coeff[1]

<img src = Quiz6/15.jpg>

In [22]:
# Error in Low-Rank Approximation
sigma = np.array([1.9, 1.1, 0.7, 0.5, 0.0])
k = 2
sigma[k]

0.7

<img src = Quiz6/23.jpg>
<img src = Quiz6/16.jpg>

In [26]:
# Obtain the SVD from eigendecomposition
A1 = np.array([[-0.87, -0.49],
               [-0.49, 0.87]])
A2 = np.array([[11, 0],
               [0, 7]])
A3 = np.array([[-0.87, -0.49],
               [-0.49, 0.87]])
ATA = A1 @ A2 @ A3
V = la.eig(ATA)
V
A1          

array([[-0.87, -0.49],
       [-0.49,  0.87]])

Compare Time complexity
<img src = Quiz6/18.jpg>

<img src = Quiz6/19.jpg>

In [28]:
# Size of low-rank approximation
m = 87
n = 29
r = 5

r*m+r*n+r

585

In [29]:
m = 90
n = 60
r = 4

r*m+r*n+r

604

SVD and rank-1 approximation
<img src = Quiz6/20.jpg>

<img src = Quiz6/21.jpg>

In [30]:
# Singular values
m = 45
n = 58

min(m,n)

45

<img src = Quiz6/22.jpg>

In [31]:
# find the best line
t = np.array([5, -2, -3.2, -0.9])
y = np.array([15.3, -6.1, -9, -2.9])
A = np.vstack([t, np.ones(len(t))]).T

m, b = la.lstsq(A, y)[0]
m,b

<ipython-input-31-1534b878945b>:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  m, b = la.lstsq(A, y)[0]


(3.003144851877476, 0.1508648342663057)

<img src =Quiz6/24.jpg>

In [33]:
# calculate least squares solution using SVD
U = np.array([[1, 0],
              [0, -1]])
S = np.array([9])
VT = np.array([[1, 1],
               [-1, 1]]) / np.sqrt(2)
b = np.array([4, 0])        
temp1 = np.divide(np.dot(U.T, b), S)
weights_linear = np.dot(VT.T, temp1)
weights_linear

array([0.31426968, 0.31426968])