In [8]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as sla

<img src = 'Quiz3/1.png'>

In [23]:
# LU Solve Time Complexity
N_M = 800
t1 = 10
t2 = 6

N_A = 4000
b = 40
t_factorization = N_A**3/N_M**3 * t1
t_solve = N_A ** 2 / N_M **2 * t2 *b
t = t_factorization + t_solve
t

7250.0

<img src = 'Quiz3/2.jpg'>

In [54]:
# Estimate Error from Monte Carlo

def check(xy):
    x = xy[0]
    y = xy[1]
    n = 1.5
    c = 1
    if np.cbrt((x-n) ** 2) + (1 - (x - n)**2)**0.5 + c >= y and np.cbrt((x-n) ** 2) - (1 - (x - n)**2)**0.5 + c <= y:
        return 1
    else:
        return 0


x = 3
y = 3
sample = [(2.0, 2.0), (2.0, 1.0), (1.5, 1.5), (0.5, 0.5), (1.5, 2.5), (1.0, 2.0), (1.0, 1.5)]
n_in = sum([check(i) for i in sample])
area = n_in / len(sample) * x * y
abs_error = abs(area - np.pi)
rel_error = abs_error / np.pi
print("abs_error:" + str(abs_error), "rel_error" + str(rel_error))

abs_error:3.2869787749816357 rel_error1.0462778397529402


<img src = 'Quiz3/3.jpg'>

In [11]:
array = np.array([ [0, 13, 0, 5, -13, 0, 0],
                   [0, 2, 0, -6, 4, 0, 7],
                   [-14, 0, 0, 0, 0, 0, 14],
                   [0, 0, 0, 0, 0, -6, 0],
                   [0, 0, 0, -10, -9, 0, 0],
                   [-12, -3, -11, 0, 0, 14, 0],
                   [-15, 0, -6, 0, 0, -12, -9]])
la.norm(array,1)
# np.max(np.sum(np.abs(array), axis = 0)) 

41.0

<img src = 'Quiz3/4.jpg'>


Entry with largest abs_value in the first column

<img src = 'Quiz3/5.jpg'>

In [51]:
n = 800
error = 1e-3
objective_error = 1e-7
(error * np.sqrt(n) / objective_error)**2

80000000000.00002

<img src = 'Quiz3/6.jpg'>

<img src = 'Quiz3/7.jpg'>

In [38]:
A = np.array([[5, 6],[25,42]])

def lu_decomp(A):
    """(L, U) = lu_decomp(A) is the LU decomposition A = L U
       A is any matrix
       L will be a lower-triangular matrix with 1 on the diagonal, the same shape as A
       U will be an upper-triangular matrix, the same shape as A
    """
    n = A.shape[0]
    if n == 1:
        L = np.array([[1]])
        U = A.copy()
        return (L, U)

    A11 = A[0,0]
    A12 = A[0,1:]
    A21 = A[1:,0]
    A22 = A[1:,1:]

    L11 = 1
    U11 = A11

    L12 = np.zeros(n-1)
    U12 = A12.copy()

    L21 = A21.copy() / U11
    U21 = np.zeros(n-1)

    S22 = A22 - np.outer(L21, U12)
    (L22, U22) = lu_decomp(S22)

    L = np.block([[L11, L12], [L21, L22]])
    U = np.block([[U11, U12], [U21, U22]])
    return (L, U)
lu_decomp(A)


(array([[1., 0.],
        [5., 1.]]),
 array([[ 5.,  6.],
        [ 0., 12.]]))

<img src = 'Quiz3/8.jpg'>

In [14]:
import numpy.linalg as la

relErr = la.norm(x1-x2,p) / la.norm(x1,p)

NameError: name 'x1' is not defined

<img src = 'Quiz3/9.jpg'>

In [ ]:
def genRandomVect():
    # define return numpy array
    arr = np.arange(100)
    np.random.shuffle(arr)
    
    return arr[:50]
genRandomVect().shape

(50,)

In [35]:
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i]
        for j in range(i):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x

def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x

def lu_solve(L, U, b):
    """x = lu_solve(L, U, b) is the solution to L U x = b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same size as L
       b must be a vector of the same leading dimension as L
    """
    y = forward_sub(L, b)
    x = back_sub(U, y)
    return x

In [52]:
L = np.array([[1, 0, 0],
            [8, 1, 0],
            [0, 9, 1]])
U = np.array([[4, 0, 0],
            [0, 1, 4],
            [0, 0, 6]])
b = np.array([2, 7, 0])
x = lu_solve(L, U, b)
x

array([  0.5, -63. ,  13.5])

In [ ]:
import numpy as np
n = 100000
V = 6 * 6 * 2
x = 6 * np.random.rand(n) - 3
y = 6 * np.random.rand(n) - 3
z = 2 * np.random.rand(n)

def check_in(x, y, z):
    if abs(x) + abs(y) < 3 and z > 0 and z < f(x,y):
        return 1
    return 0

n_in = np.sum(np.array([check_in(x[i], y[i], z[i]) for i in range(n)]))
volume = V * n_in/n

array([-0.248757  ,  2.88472812, -2.48550598, -1.26783462,  1.62932789,
       -2.38658379, -2.96965764, -0.6040536 ,  0.93694768, -1.46779776])

<img src = 'Quiz3/10.jpg'>

In [49]:
a = np.array([32,10,24,22,20,27,26,29,33,25])
L = 26
U = 30.5
b = a[a<=U]
c = b[b>=L]
len(c)/len(a)

0.3

<img src = 'Quiz3/11.jpg'>

In [55]:
n = 800
error = 1e-2
total = 8e10
error * np.sqrt(n) / np.sqrt(total)

1e-06

In [34]:
arr = np.arange(100)
np.random.shuffle(arr)
arr[:50]

array([27, 55, 59, 77, 41,  5, 95, 68, 58, 29, 36, 44, 94, 16, 26,  3, 70,
       96, 19, 37, 99, 42,  9, 62, 80, 76,  0, 49,  7, 12, 72, 35,  8, 65,
       71, 54, 85, 43, 24, 20, 81, 14, 46, 60,  2, 88, 64, 52, 98, 53])

In [ ]:
import numpy as np
import numpy.linalg as la

attr = np.array([get_movie_attr(j) for j in range(k)])
rates = np.array([get_ratings(i) for i in range(n)]).T
prefs = la.solve(attr, rates)

In [53]:
L = np.array([[1, 0, 0],
            [8, 1, 0],
            [0, 9, 1]])
U = np.array([[4, 0, 0],
            [0, 1, 4],
            [0, 0, 6]])
L@U

array([[ 4,  0,  0],
       [32,  1,  4],
       [ 0,  9, 42]])

In [58]:
def check(xy):
    x = xy[0]
    y = xy[1]

    if abs(x-0.5)<=y and np.sqrt(x)+0.5 >= y:
        return 1
    else:
        return 0


x = 3
y = 3
sample = [(2.0, 0.5), (1.0, 1.0), (2.0, 1.0), (1.5, 0.5), (0.5, 0.5), (1.5, 2.0)]
n_in = sum([check(i) for i in sample])
area = n_in / len(sample) * x * y

print("Area " + str(area))

Area 3.0
