In [1]:
import numpy as np
import numpy.linalg as la
from sympy import *

In [2]:
def hessian(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Hessian = A.jacobian(B).jacobian(B).subs({x:x0, y:y0})
    return np.array(Hessian).astype(np.float64)

def gradient(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Gradient = A.jacobian(B).subs({x:x0, y:y0})
    return np.array(Gradient).astype(np.float64).T

def newtons_method(f, x_init, tol):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    cnt = 0
    while(la.norm(gradient(f, x_new)) > tol):
        x_prev = x_new
        print(x_prev)
        s = -la.solve(hessian(f, x_prev), gradient(f, x_prev))
        x_new = x_prev + s
        print(x_new)
        cnt += 1
    return x_new, cnt

<img src = 'Quiz5/1.png'>

In [68]:
# Sample Optimization ND NewtonMethod one step
x, y = symbols('x y')
x0 = np.array([[1], [2]])
f = 2 * x**2 + 3 * y**3
H = hessian(f, x0)
s = -la.solve(H, gradient(f, x0))
print('Hessian: %s' %H)
print('Step: %s'%s)
x1 = x0 + s
print('x1: %s' %x1)

Hessian: [[ 4.  0.]
 [ 0. 36.]]
Step: [[-1.]
 [-1.]]
x1: [[0.]
 [1.]]


In [67]:
x, y = symbols('x y')
x0 = np.array([[2], [3]])
f = 5 * x**3 + 4 * y**4
H = hessian(f, x0)
s = -la.solve(H, gradient(f, x0))
print('Hessian: %s' %H)
print('Step: %s'%s)
x1 = x0 + s
print('x1: %s' %x1)

Hessian: [[ 60.   0.]
 [  0. 432.]]
Step: [[-1.]
 [-1.]]
x1: [[1.]
 [2.]]


<img src = 'Quiz5/2.png'>

In [18]:
# Sample Finite Difference Gradient
x, y, z = symbols('x y z')
X0 = np.array([1, 1, 1])
phi = Matrix([x**2 * y + x + y * z**2])
h = 0.1

phi0 = np.array(phi.subs({x:X0[0], y:X0[1], z:X0[2]})).astype(np.float64)
for i in range(3):
    a = np.zeros(3)
    a[i] = h
    X = X0 + a
    phix = np.array(phi.subs({x:X[0], y:X[1], z:X[2]})).astype(np.float64)
    print((phi0-phix)/h)

[[-3.1]]
[[-2.]]
[[-2.1]]


In [111]:
x, y, z = symbols('x y z')
X0 = np.array([1, 1, 1])
phi = Matrix([x * y + x*z + z**2])
h = 0.1

phi0 = np.array(phi.subs({x:X0[0], y:X0[1], z:X0[2]})).astype(np.float64)
for i in range(3):
    a = np.zeros(3)
    a[i] = h
    X = X0 - a
    phix = np.array(phi.subs({x:X[0], y:X[1], z:X[2]})).astype(np.float64)
    print(-(phi0-phix)/h)

[[-2.]]
[[-1.]]
[[-2.9]]


<img src = 'Quiz5/3.jpg'>
<img src = 'Quiz5/19.jpg'>

<img src = 'Quiz5/4.jpg'>

In [19]:
# Sample Determine the length of the interval
x = Symbol('x')
f = (x - 5) ** 3
L = -12
R = 12
iteration = 3

for i in range(iteration):
    mid = (L + R) /2
    fL = f.subs(x,L)
    fR = f.subs(x,R)
    fmid = f.subs(x,mid)
    if fL * fmid <= 0:
        R = mid
    else:
        L = mid
R - L

3.0

In [69]:
x = Symbol('x')
f = (x - 4) ** 3
L = -11
R = 12
iteration = 3

for i in range(iteration):
    mid = (L + R) /2
    fL = f.subs(x,L)
    fR = f.subs(x,R)
    fmid = f.subs(x,mid)
    if fL * fmid <= 0:
        R = mid
    else:
        L = mid
R - L

2.875

<img src = 'Quiz5/5.jpg'>

In [22]:
# Sample Perform One Step of Golden Section Search
def f(x):
    return (x-6.7)**2
gs = (np.sqrt(5) - 1) / 2
a = -3
b = 8
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)

# Begin your modifications below here
f1, f2 = f(m1), f(m2)
if f1>= f2:
    a = m1
else:
    b = m2
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)    
if f1>= f2:
    f1 = f2
    f2 = f(m2)
else:
    f2 = f1
    f1 = f(m1)
print(a, b)

1.201626123751156 8


<img src = 'Quiz5/6.jpg'>

In [27]:
# Sample Carrying out Newton steps
x0 = 0.3
x = Symbol('x')
f = -exp(-x**2)
df = diff(f,x,1)
d2f = diff(f, x, 2)
x1 = x0 - (df/d2f).subs(x, x0)
x1

-0.0658536585365854

In [112]:
x0 = 0.35
x = Symbol('x')
f = 4*cos(x)**3
df = diff(f,x,1)
d2f = diff(f, x, 2)
x1 = x0 - (df/d2f).subs(x, x0)
x1

-0.147647330090561

<img src = 'Quiz5/7.jpg'>

In [39]:
# Sample
x, y = symbols('x y')
E = Matrix([[6*x**3 + 5 * y**2 - 6], [3 * x**4 + 4 * y -5]])
Y = Matrix([x, y])
J = E.jacobian(Y)
X0 = np.array([1, -1])
J0 = np.array(J.subs({x:X0[0], y:X0[1]})).astype(np.float64)
print(J0)
E0 = np.array(E.subs({x:X0[0], y:X0[1]})).astype(np.float64)
S = la.solve(J0, -E0)
S.flatten()+X0

[[ 18. -10.]
 [ 12.   4.]]


array([ 1.20833333, -0.125     ])

In [63]:
x, y = symbols('x y')
E = Matrix([[4*x**2 + 2 * y**3 - 6], [6 * x**4 + 3 * y -5]])
X0 = np.array([1, 0])

Y = Matrix([x, y])
J = E.jacobian(Y)
J0 = np.array(J.subs({x:X0[0], y:X0[1]})).astype(np.float64)
print(J0)
E0 = np.array(E.subs({x:X0[0], y:X0[1]})).astype(np.float64)
S = la.solve(J0, -E0)
S.flatten()+X0

[[ 8.  0.]
 [24.  3.]]


array([ 1.25      , -2.33333333])

<img src = 'Quiz5/8.jpg'>
<img src = 'Quiz5/13.jpg'>

<img src = 'Quiz5/9.jpg'>

In [ ]:
import numpy as np

def f(x):
    return x[0]**3+x[1]**2+x[2]**5+x[3]**3+x[4]*x[6]+x[5]*x[6]+x[6]**2+x[7]**3
n = 8
h = 0.4
y0 = f(xvec)
gradient = []
for i in range(n):
    a = np.zeros(n)
    a[i] = h
    gradient.append((f(xvec+a) - y0) / h) # forward finite difference
approx_gradient = np.array(gradient)

<img src = 'Quiz5/10.jpg'>

In [ ]:
import numpy as np
from sympy import *

x = Symbol('x')
f = 160 - (x**3/60 + x**2 + 40*cos(x) + 50*x)
df = diff(f,x)
t = [t_initial]

t.append(t_initial - (f/df).subs(x, t_initial))
while abs(t[-1] - t[-2]) >= epsilon:
    tnext = t[-1] - (f/df).subs(x, t[-1])
    t.append(tnext)
t = t[1:]

<img src = 'Quiz5/11.jpg'>

In [46]:
# Sample Carrying out Newton steps (n-dimensional)
x, y  = symbols('x y')
f = exp(8*x) + 6 * cos(y)
X0 = np.array([[0], [np.pi]])
H = hessian(f, X0)
g = gradient(f, X0)
s = -la.solve(H, g)
X_new = X0 + s
X_new

array([[-0.125     ],
       [ 3.14159265]])

In [113]:
x, y  = symbols('x y')
f = exp(9*x) + 4 * cos(y)
X0 = np.array([[0], [np.pi]])
H = hessian(f, X0)
g = gradient(f, X0)
s = -la.solve(H, g)
X_new = X0 + s
X_new

array([[-0.11111111],
       [ 3.14159265]])

<img src = 'Quiz5/12.jpg'>

In [70]:
# Sample: Determine the length of the interval after one iteration
L = -8
R = 10
length_0 = R - L
length_1 = length_0 * (np.sqrt(5) - 1)/2
length_1

11.124611797498108

In [115]:
# Same as Golden Section Interval
L = -2
R = 6
length_0 = R - L
length_1 = length_0 * (np.sqrt(5) - 1)/2
length_1

4.944271909999159

<img src = 'Quiz5/14.jpg'>

In [55]:
# Sample Perform Two Steps of Newton's Method
x = Symbol('x')
f = x**3 + 4*x -5
x0 = 0
df = diff(f)
for i in range(2):
    # x_new = x0 - (f/df).subs(x,x0)
    # x0 = np.float(x_new)
    # print(x0)
    x0 -= float((f/df).subs(x, x0))
    print(x0)

1.25
1.025179856115108


In [114]:
x = Symbol('x')
f = x**3 - 4*x -7
x0 = 0
df = diff(f)
for i in range(2):
    # x_new = x0 - (f/df).subs(x,x0)
    # x0 = np.float(x_new)
    # print(x0)
    x0 -= float((f/df).subs(x, x0))
    print(x0)

-1.75
-0.7168674698795181


<img src = 'Quiz5/15.jpg'>
<img src = 'Quiz5/16.jpg'>
<img src = 'Quiz5/25.jpg'>
<img src = 'Quiz5/26.jpg'>


<img src = 'Quiz5/17.jpg'>

In [73]:
# Finite Difference: Calculation R -> R
x = Symbol('x')
y = -log(x)
x0 = 0.1
h = 0.01
(y.subs(x, x0+h) - y.subs(x, x0-h))/2/h

-10.0335347731076

<img src = 'Quiz5/18.jpg'>

In [ ]:
import numpy as np

L = 0
R = max_wood
intervals = [(L, R)]
T_L = get_temperature(L)
T_R = get_temperature(R)

while abs(T_L - 375) >= epsilon and abs(T_R - 375) >= epsilon:
    mid = (L + R) / 2
    T_mid = get_temperature(mid)
    if T_mid - 375 < 0:
        T_L = T_mid
        L = mid
        intervals.append((L,R))
    else:
        T_R = T_mid
        R = mid
        intervals.append((L,R))

if abs(T_L - 375) < epsilon:
    weight = L
elif abs(T_R - 375) < epsilon:
    weight = R

<img src = 'Quiz5/20.jpg'>

In [72]:
# Sample Newton Solve
x, y = symbols('x y')
A = np.array([[3, -2, 2, 1, 3, -3],
              [-1, 3, -1, 0, -1, 1]])
X = np.array([x**2, x, 1, y**2, y, x*y])
X0 = np.array([-2, -1])

f = Matrix(A @ X)
Y = Matrix([x, y])
J = (f.jacobian(Y))

J_ = np.array(J.subs({x:X0[0], y:X0[1]})).astype(np.float64)
print(J_)
f_ = np.array(f.subs({x:X0[0], y:X0[1]})).astype(np.float64)

S = la.solve(J_, -f_)
S.flatten()+X0

[[-11.   7.]
 [  6.  -3.]]


array([0.88888889, 2.11111111])

<img src = 'Quiz5/21.jpg'>

In [92]:
from sympy import *
import numpy as np
import numpy.linalg as la

x, y, z = symbols('x y z')
w = Matrix([x, y, z])
X = Matrix([[16*x**4 + 16*y**4 + z**4 - 16],
            [x**2    + y**2    + z**2 - 3],
            [x**3    - y]])

w0 = np.array([1, 1, 1])
J = (X.jacobian(w))
guesses = np.zeros((5,3))
for i in range(5):
    J_ = np.array(J.subs({x:w0[0], y:w0[1], z:w0[2]})).astype(np.float64)
    X_ = np.array(X.subs({x:w0[0], y:w0[1], z:w0[2]})).astype(np.float64)
    S = la.solve(J_, -X_)
    guesses[i,:] = S.flatten()+w0
    w0 = guesses[i, :]

array([[0.92916667, 0.7875    , 1.28333333],
       [0.88707453, 0.69317586, 1.32086464],
       [0.8782444 , 0.67719471, 1.3306098 ],
       [0.87796599, 0.6767573 , 1.33085521],
       [0.87796576, 0.67675697, 1.33085541]])

<img src = 'Quiz5/22.jpg'>

In [96]:
# Sample N-Dimension Optimization using Steepest Descent
x, y = symbols('x y')
f = 13*x**2 + 7*x*y + 13*y**2 + 13*sin(y)**2 + 7*cos(x*y)
X0 = np.array([[-3], [3]])
alpha = 0.05
s0 = -gradient(f, X0)
print(s0)
X1 = X0 + alpha*s0
X1

[[ 48.34551181]
 [-44.71311033]]


array([[-0.58272441],
       [ 0.76434448]])

<img src = 'Quiz5/23.jpg'>

In [101]:
# Sample Perform Two Steps of Bisection
f = lambda x: (x-6.7)**5
L = -7
R = 12
f_L = f(L)
f_R = f(R)

for i in range(2):
    mid = (L + R)/2
    f_mid = f(mid)
    if sign(f_L) == sign(f_mid):
        L, f_L = mid, f_mid
        print(L, R)
    else:
        R, f_R = mid, f_mid
        print(L, R)


2.5 12
2.5 7.25


<img src = 'Quiz5/24.jpg'>

In [110]:
# Sample Newton Solve 2
x, y = symbols('x y')
x0 = np.array([-2, 1])
X = Matrix([2*x*y+4, x**3 + y**2 + 2])
Y = Matrix([x, y])
J = f.jacobian(Y)
J_ = np.array(J.subs({x:x0[0], y:x0[1]})).astype(np.float64)
X_ = np.array(f.subs({x:x0[0], y:x0[1]})).astype(np.float64)
S = la.solve(J_, -X_)
S.flatten()+x0

array([-1.61538462,  1.19230769])

<img src = 'Quiz5/27.jpg'>
<img src = 'Quiz5/29.jpg'>
<img src = 'Quiz5/28.jpg'>