In [2]:
import numpy as np
import scipy.linalg as la

<img src ='Quiz4/1.jpg'>

In [2]:
a = np.array([6, 8, 3])
a / la.norm(a, 1)

array([0.35294118, 0.47058824, 0.17647059])

<img src = 'Quiz4/2.jpg'>

In [5]:
lamda1 = 4
lamda2 = -1
x = abs(lamda2 / lamda1)
if x > 1:
    x = 1/x
factor = x
count = 1
while x > 1e-2:
    x *= factor
    count += 1
count

4

In [4]:
lamda1 = -3
lamda2 = 5
x = abs(lamda2 / lamda1)
if x > 1:
    x = 1/x
factor = x
count = 1
while x > 1e-2:
    x *= factor
    count += 1
count


10

<img src = 'Quiz4/3.jpg'>

In [9]:
A = 4
B = 16
factor = 1e-4
A*B*factor

0.0064

<img src = 'Quiz4/15.jpg'>

In [11]:
np.log10(1e-10*1e4)

-6.0

<img src = 'Quiz4/4.jpg'>

<img src = 'Quiz4/5.jpg'>

In [11]:
x1 = 2
x2 = 4 
x3 = 6
Ax1 = 40
Ax2 = 40
Ax3 = 180

X = np.array([x1, x2, x3])
AX = np.array([Ax1, Ax2, Ax3])
A = AX/X
np.max(A) / np.min(A)

3.0

In [60]:
x1 = 2
x2 = 3
x3 = 6
Ax1 = 60
Ax2 = 60
Ax3 = 30

X = np.array([x1, x2, x3])
AX = np.array([Ax1, Ax2, Ax3])
A = AX/X
np.max(A) / np.min(A)

6.0

<img src = 'Quiz4/6.jpg'>

In [18]:
def convert(B):
    index = np.where(~B.any(axis=0))[0]
    B[:,index] += 1
    Mb = B / np.sum(B, axis = 0)
    return Mb
A = np.array([[0, 1, 1],
              [0, 0, 0],
              [1, 1, 0]])
alpha = 0.75
S = convert(A)
G = alpha * S + (1-alpha)/A.shape[0]
G

array([[0.08333333, 0.45833333, 0.83333333],
       [0.08333333, 0.08333333, 0.08333333],
       [0.83333333, 0.45833333, 0.08333333]])

In [2]:
def convert(B):
    index = np.where(~B.any(axis=0))[0]
    B[:,index] += 1
    Mb = B / np.sum(B, axis = 0)
    return Mb

A = np.array([[0, 1, 1, 1],
              [1, 0, 0, 0],
              [0, 0, 0, 1],
              [1, 1, 1, 0]])
alpha = 0.75
S = convert(A)
G = alpha * S + (1-alpha)/A.shape[0]
G

array([[0.0625, 0.4375, 0.4375, 0.4375],
       [0.4375, 0.0625, 0.0625, 0.0625],
       [0.0625, 0.0625, 0.0625, 0.4375],
       [0.4375, 0.4375, 0.4375, 0.0625]])

<img src = 'Quiz4/7.jpg'>

In [7]:
lama1 = 3
lama2 = 2
coeff = 1
sigma = 4

lama = np.array([lama1, lama2])
lamb = lama - sigma
print('larger eigen = %s' %np.max(lamb))
print('smaller eigen = %s' %np.min(lamb))

larger eigen = -1
smaller eigen = -2


In [6]:
lama1 = 8
lama2 = 4
coeff = 3
sigma = 3

lama = np.array([lama1, lama2])
lamb = coeff * lama - sigma
print('larger eigen = %s' %np.max(lamb))
print('smaller eigen = %s' %np.min(lamb))

larger eigen = 21
smaller eigen = 9


<img src = 'Quiz4/8.jpg'>

In [35]:
import numpy as np

mat = np.array([[0, 1, 1, 1, 0],
                [1, 0, 0, 1, 0],
                [1, 1, 0, 1, 0],
                [1, 0, 0, 0, 1],
                [1, 0, 1, 0, 0]])
mat = mat / np.sum(mat, axis = 0)
a = np.linalg.eig(mat)[1][:, 0].astype(np.float64)
prob = a/np.sum(a)

<ipython-input-35-ac2e08e29dec>:9: ComplexWarning: Casting complex values to real discards the imaginary part
  a = np.linalg.eig(mat)[1][:, 0].astype(np.float64)


<img src = 'Quiz4/9.jpg'>

In [33]:
import numpy as np

A = np.zeros(A_csr.shape)

for i in range(1, A_csr.indptr.shape[0]):
    count = A_csr.indptr[i] - A_csr.indptr[i - 1]
    for j in range(count):
        column = A_csr.indices[A_csr.indptr[i - 1] + j]
        value = A_csr.data[A_csr.indptr[i - 1] + j]
        A[i-1][column] = value

0
1
2
3
4


<img src = 'Quiz4/10.jpg'>

In [ ]:
import numpy as np
import numpy.linalg as la

err_xhat = xtrue - xhat
rel_err_xhat = la.norm(err_xhat, 2) / la.norm(xtrue, 2)
err_Axhat = A @ err_xhat
rel_err_Axhat = la.norm(err_Axhat, 2) / la.norm(A @ xtrue, 2)
cond_A = la.norm(A, 2) * la.norm(la.inv(A), 2)
bound_rel_err_Axhat = cond_A * rel_err_xhat

<img src = 'Quiz4/11.jpg'>

<img src = 'Quiz4/12.jpg'>
<img src = 'Quiz4/13.jpg'>

<img src = 'Quiz4/14.jpg'>

In [4]:
lam = 2
lamb = lam**3 -2 * lam**2 - 9* lam + 15
lamb

-3

<img src = 'Quiz4/16.jpg'>
<img src = 'Quiz4/17.jpg'>

In [ ]:
import numpy as np
import numpy.linalg as la

A_complete = A.copy()
A_complete[missing_row_index] = 1 - np.sum(A, axis = 0)
A_complete[missing_row_index][missing_col_index] = 0
col = (comp2 - A_complete @ comp1) / comp1[missing_col_index]
A_complete[:, missing_col_index] = col



def final_comp(A):
    # complete your function
    # return 1d numpy array with final ingredient composition
    '''
    eig = la.eig(A)
    arr = eig[0]
    idx = np.argmin(abs(arr-1))
    x = eig[1][idx]
    '''
    comp = np.random.rand(A.shape[0])
    comp /= la.norm(comp,1)
    while not np.array_equal(A @ comp, comp):
        comp = A @ comp
    return comp

<img src = 'Quiz4/18.jpg'>

<img src = 'Quiz4/19.jpg'>

In [10]:
lam = np.array([3, 12, 91])
sigmas = [-88.1, 1, -94, 91.1, -7, -4]
temp = np.inf
idx = 0
for i in range(len(sigmas)):
    sigma = sigmas[i]
    lam_new = abs(lam+sigma)
    lam_new = np.sort(lam_new)
    print("Number %s" %i)
    print(lam_new[0],lam_new[1])
    e = lam_new[0]/lam_new[1]
    print(e)
    if e < temp:
        temp = e
        idx = i
    print(temp)
sigmas[idx]

Number 0
2.9000000000000057 76.1
0.038107752956636085
0.038107752956636085
Number 1
4 13
0.3076923076923077
0.038107752956636085
Number 2
3 82
0.036585365853658534
0.036585365853658534
Number 3
94.1 103.1
0.9127061105722599
0.036585365853658534
Number 4
4 5
0.8
0.036585365853658534
Number 5
1 8
0.125
0.036585365853658534


-94

In [4]:
sigma = 6
lams = np.array([[15, 7, -7],
                 [-13, 7, -7],
                 [-7, 8, 15],
                 [15, -13, -7],
                 [8, 7, 15]])
temp = np.inf
idx = 0
for i in range(lams.shape[0]):
    lam = lams[i]
    lam_new = abs(lam-sigma)
    lam_new = np.sort(lam_new)
    e = lam_new[0] / lam_new[1]
    print(e)
    if e < temp:
        temp = e
        idx = i
    print(temp)
lams[idx]

0.1111111111111111
0.1111111111111111
0.07692307692307693
0.07692307692307693
0.2222222222222222
0.07692307692307693
0.6923076923076923
0.07692307692307693
0.5
0.07692307692307693


array([-13,   7,  -7])

In [8]:
A = np.zeros((4,4))
value = [1.8, 2, -4.9, -1.6]
for i in range(len(value)):
    A[i,i] = value[i]
np.linalg.cond(A, 2)

3.0625

In [13]:
lam1, lam2, lam3 = -6,5,4
u = np.array([1, 0, -1])
x0 = np.array([-1, -1, -1])
sigma = 2
n = 4

e0 = la.norm(x0 - u, np.inf)
lams = np.array([lam1, lam2, lam3])
def find_convergence(lams, sigma= 0):
    new_lams = list(lams - sigma)
    new_lams.sort(key = abs)
    return abs(new_lams[0] / new_lams[1])
find_convergence(lams) ** (n) * e0, find_convergence(lams, sigma) ** (n) *e0

(0.8192000000000002, 0.39506172839506165)

In [4]:
A = np.array([[8, -5],
              [0, 3]])
a = la.eig(A)[1]
ans = np.zeros(a.shape)
for i in range(A.shape[1]):
    vector = a[:, i] / la.norm(a[:, i],1)
    ans[:,i] = vector
ans

array([[1. , 0.5],
       [0. , 0.5]])