In [1]:
import numpy as np

In [ ]:
# 3.1
import numpy as np

team_names = list(set(home_team))    # list team names here
n = len(team_names)
A = np.zeros((n,n))                  # the rows and columns should have the same order as your team_names
games = list(zip(home_team, away_team))
scores = list(zip(home_score, away_score))
for i in range(len(games)):
    winning_team_index = np.argmax(scores[i])
    losing_team_index = np.argmin(scores[i])
    winning_team = games[i][winning_team_index]
    losing_team = games[i][losing_team_index]
    winning_idx_A = team_names.index(winning_team)
    losing_idx_A = team_names.index(losing_team)
    A[winning_idx_A][losing_idx_A] += abs(scores[i][0] - scores[i][1])


In [ ]:
# 3.2
import numpy as np

def transition(A):
    # construct the matrix M
    M = np.zeros(A.shape)
    for i in range(len(M)):
        s = sum(A[:,i])
        if (s == 0):
            M[:, i]=1 / (M.shape[0])
        else:
            M[:, i]=A[:,i] / s
    return M

M = transition(A)

In [ ]:
# 3.3
import numpy as np
import scipy.linalg as la

def power_iteration(M,tol):
    # compute things!
    n = M.shape[0]
    x0 = np.random.uniform(size = n)
    x0 = x0/la.norm(x0, 1)
    x_i = x0.copy()
    x_i_1 = M @ x_i
    x_i_1 /= la.norm(x_i_1, 1)
    while la.norm(x_i_1 - x_i, 2) > tol:
        x_i = x_i_1
        x_i_1 = M @ x_i_1
        x_i_1 /= la.norm(x_i_1, 1)
    x = x_i
    return x

xstar = power_iteration(M, tol)

In [ ]:
# 3.4
import numpy as np
import matplotlib.pyplot as plt

m = power_iteration(M,tol)
l = list(zip(team_names,m))
l.sort(key = lambda i:i[1],reverse = True)
team_ranks = [i[0] for i in l]
bar_height = [i[1] for i in l]

y_label = team_ranks


f, axs = plt.subplots(1,1,figsize=(8,10))
plt.subplots_adjust(left=0.25)
y_axis = range(len(team_ranks))
plt.barh(y_axis, bar_height)
plt.yticks(y_axis, y_label)
plt.title(season_name + ' season NBA teams ranking based on first 150 games')
axs.invert_yaxis()

In [7]:
a = np.array(['23','23','323'])
b = np.array([1,3,4])
list(zip(a,b))
list(a).index('23')

0

In [17]:
A = np.zeros((5,5))
B = A - np.eye(5) - np.random.uniform(-2,2,(5,5))
print(B)
x = B[:,1]
f_x = np.exp(x) / np.sum(np.exp(x))
B[:,1] = f_x
print(B)

[[-2.35956528 -0.50943754  1.68894352  1.83268122  0.91407127]
 [ 1.8594649  -1.58025671 -0.82472949 -1.71948695  0.46479111]
 [ 0.42610678  1.55035717 -1.82339381 -1.23428464 -1.2605956 ]
 [-0.48520254  1.70497789 -0.1607629  -2.01735171  1.4439421 ]
 [-0.57524662  0.91254852  0.0443131   1.10072082 -2.04241149]]
[[-2.35956528  0.0444672   1.68894352  1.83268122  0.91407127]
 [ 1.8594649   0.01524014 -0.82472949 -1.71948695  0.46479111]
 [ 0.42610678  0.34881667 -1.82339381 -1.23428464 -1.2605956 ]
 [-0.48520254  0.40714411 -0.1607629  -2.01735171  1.4439421 ]
 [-0.57524662  0.18433188  0.0443131   1.10072082 -2.04241149]]


In [100]:
x = np.arange(6)+1
np.random.shuffle(x)
x = list(enumerate(x))
x.sort(key = lambda x: x[1])
print(x)
idx = np.array(list(list(zip(*x))[0]))
idx.shape

[(0, 1), (4, 2), (1, 3), (5, 4), (2, 5), (3, 6)]


(6,)