In [9]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
from sympy import *

In [48]:
def n_degree_taylor(formula, x, x_0, n):
    '''
    Given the analytic expression, x and x_0, calculate
    its nth degree Taylor polynomial
    Note: Variable is defaulted to x
    '''
    var_x = Symbol('x')
    acc = 0
    # Be careful, n+1 because it's up to n
    for i in range(n+1):
        acc += diff(formula, var_x, i).subs(var_x, x_0)/factorial(i)*(x-x_0)**i
    return float(acc)

In [47]:
def n_degree_taylor_derivative(formula, x, x_0, n, n_d):
    '''
    Given the analytic expression, x and x_0, calculate
    its n_d-th derivative based on n-th degree Taylor polynomial
    Note: Variable is defaulted to x
    
    Parameters:
    formula -- analytic expression in sympy
    x -- desired point
    x_0 -- expansion point
    n -- highest degree of polynomial
    n_d -- degree of derivative

    Returns:
    n_d-th derivative based on n-th degree Taylor polynomial
    '''
    var_x = Symbol('x')
    acc = 0
    # Be careful, n+1 because it's up to n
    for i in range(n+1):
        acc += diff(formula, var_x, i).subs(var_x, x_0)/factorial(i)*(var_x-x_0)**i
    derivative = diff(acc, var_x, n_d)
    return float(derivative.subs(var_x, x))

In [46]:
def decimal_to_floating_point(x, n, p):
    """
    Convert a positive decimal number x into its normalized floating-point
    form.
    
    Parameters
    ----------
    x: float
        Input positive decimal number
    n: int
        Number of binary bits in fraction
    p: int
        Exponent range

    Returns
    -------
    f: str
        String of length n representing the fraction part of x in the given floating-point system
    m: int
        Exponent of x in the given floating-point system
    """

    # your implementation goes here

    integer_part = int(x)
    decimal_part = x - integer_part
    int_bin = bin(integer_part)[2:]

    def dec2bin(x):
        x -= int(x)
        bins = []

        while x:
            x *= 2
            bins.append(1 if x>=1. else 0)
            x -= int(x)

        return bins
    decimal_bins = dec2bin(decimal_part)
    if integer_part != 0:
        m = len(str(int_bin)) - 1
        f = str(int_bin)[1:]
        for i in decimal_bins:
            f += str(i)
        if len(f) > n:
            f = f[:n]
        elif len(f) < n:
            f += (n - len(f)) * '0'

    if integer_part == 0:
        m = -(decimal_bins.index(1) + 1)
        f = ''
        for i in range(decimal_bins.index(1) + 1, len(decimal_bins)):
            f += str(decimal_bins[i])
        if len(f) > n:
            f = f[:n]
        elif len(f) < n:
            f += (n - len(f)) * '0'

    return f, m

def bin2dec(x):
    x = str(x)
    a = 0
    for i in range(2, len(x)):
        a += int(x[i]) * 2 ** (-i + 1)
    return a

In [51]:
def hessian(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Hessian = A.jacobian(B).jacobian(B).subs({x:x0, y:y0})
    return np.array(Hessian).astype(np.float64)

def gradient(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Gradient = A.jacobian(B).subs({x:x0, y:y0})
    return np.array(Gradient).astype(np.float64).T

def newtons_method(f, x_init, tol):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    cnt = 0
    while(la.norm(gradient(f, x_new)) > tol):
        x_prev = x_new
        print(x_prev)
        s = -la.solve(hessian(f, x_prev), gradient(f, x_prev))
        x_new = x_prev + s
        print(x_new)
        cnt += 1
    return x_new, cnt

![](img/1.jpg)

In [8]:
# Singular Values for PCA Mean
X = np.array([[-0.614, 0.896, -1.649], [0.334, -1.273, 0.538], [0.260, -0.722, -0.273], [0.142, -0.196, -1.050]])
X_zeroed = X - X.sum(axis = 0)/X.shape[0]
u, s, vt = la.svd(X_zeored)
print(X_zeroed)
s


[[-0.6445   1.21975 -1.0405 ]
 [ 0.3035  -0.94925  1.1465 ]
 [ 0.2295  -0.39825  0.3355 ]
 [ 0.1115   0.12775 -0.4415 ]]


array([2.37845489, 0.42865198, 0.01336356])

![](img/2.jpg)

In [24]:
# NewtonSolve
x, y = symbols('x y')
X = Matrix([3*x**3 + 2*y**2 - 6, 4*x**4 + 6*y - 5])
x0 = np.array([-1, 1])
Y = Matrix([x, y])
J = X.jacobian(Y)
J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
print(J_0)
x1 = x0 - la.inv(J_0) @ np.array(X.subs({x: x0[0], y: x0[1]})).astype(np.float).flatten()
x1

[[  9.   4.]
 [-16.   6.]]


array([-0.47457627,  1.56779661])

![](img/3.jpg)

In [26]:
# Low-rank Approximation
s = np.array([32, 27, 15, 3, 2])
r = 2

d = s[r]
d

15

![](img/4.jpg)

In [40]:
# Rounding Error - Decimal to Binary Floating Point
y = 14.375
n = 4
f, m = decimal_to_floating_point(14.375, 4)
print(f, m)
(1 + bin2dec(0.1101)) * 2 **m
abs((1 + bin2dec(0.1101)) * 2 **m - y)

1100 3


0.125

Ill-Conditioned Matrices
![](img/5.jpg)

![](img/6.jpg)

In [41]:
# Floating point: exact representation
n = 3
k = 2 ** (n + 1)
k

16

![](img/7.jpg)

In [42]:
# Find the Residual
u3 = np.array([0, 0, 0, 1])
u4 = np.array([0, 0, 1, 0])
b = np.array([9, 12, 5, 2])
np.sqrt((u3 @ b)**2 + (u4 @ b)**2)

5.385164807134504

Compare Computational Cost
![](../Quiz/Quiz5/3.jpg)
![](../Quiz/Quiz5/19.jpg)

![](img/8.jpg)

In [43]:
# Finding the Eigenvalues of a Matrix
A = np.array([[7, 0],
              [-5, 3]])
lam = np.array([A[0, 0], A[1, 1]])
lamb = 1/(2*lam - 4)
lamb

array([0.1, 0.5])

![](img/9.jpg)

In [44]:
# Estimating Errors of Iterative Methods
ek = 0.081096
C = 0.8

r = (1 + 5**0.5)/2
ek1 = ek ** r * C
ek1

0.013734535892124023

Shoe Store Allocation
![](img/10.jpg)

![](img/11.jpg)

In [45]:
# Shifted Inverse Iteration
lamA = np.array([8, -11, -5, 17, 2])
lamB = lamA + 12
lamB

array([20,  1,  7, 29, 14])

![](img/12.jpg)

In [50]:
# Taylor Series Approximation
n = 3
n_degree_taylor(cos(x), 2, 0, n)

-1.0

![](img/13.jpg)

![](img/14.jpg)

In [52]:
# N-Dimension Optimization using Steepest Descent
x, y = symbols('x y')
f = 11*x**2 + 14*x*y + 11*y**2 + 6*sin(y)**2 + 13*cos(x*y)
X0 = np.array([[-3], [4]])
alpha = 0.2
s0 = -gradient(f, X0)
print(s0)
X1 = X0 + alpha*s0
X1

[[ 37.90179174]
 [-72.86249328]]


array([[  4.58035835],
       [-10.57249866]])

![](img/15.jpg)

In [53]:
x, y, z = symbols('x y z')
X = Matrix([16*x**4 + 16*y**4 + z**4 - 16,
            x**2    + y**2    + z**2 - 3,
            x**3    - y])
Y = Matrix([x, y, z])
X.jacobian(Y)

Matrix([
[64*x**3, 64*y**3, 4*z**3],
[    2*x,     2*y,    2*z],
[ 3*x**2,      -1,      0]])

In [ ]:
# Newton's Method
import numpy as np
import numpy.linalg as la

def f(w):
    x, y, z = w
    return np.array([
        16*x**4 + 16*y**4 + z**4 - 16,
        x**2    + y**2    + z**2 - 3,
        x**3    - y])

def J(w):
    x, y, z = w
    return np.array([[64*x**3, 64*y**3, 4*z**3],
                     [2*x, 2*y, 2*z],
                     [3*x**2, -1, 0]])

guesses = np.zeros((5,3))

# Initial guess, don't save this in output
w = np.array([1.,1.,1.])
x = w
for i in range(5):
    x = x - la.inv(J(x)) @ f(x)
    guesses[i] = x

![](img/16.jpg)

In [70]:
# Instagram Infinity Loop
import numpy as np
import numpy.linalg as la


M = (A.T / A.sum(axis=1))
x = np.ones(A.shape[0])/A.shape[0]
while not np.array_equal(M @ x, x):
    x = M @ x

prob = x[names.index('Nancy')]

![](img/18.jpg)

In [ ]:
# Floating Point Summation
sum_p = 0.0
sum_n = 0.0
data = sorted(data,key = abs)
for i in range(len(data)):
    if data[i] > 0:
        sum_p += data[i]
    elif data[i] <= 0:
        sum_n += data[i]
data_sum = sum_p + sum_n

![](img/19.jpg)

In [72]:
# Solve rank-deficient system with SVD
import numpy as np

s = S[S!=0]
r = len(s)
# print(U.shape, S.shape, Vh.shape, r, len(b))
U_r = U[:, :r]
Vh_r = Vh[:r, :]
x = Vh_r.T @ (b @ U_r / s)

array([8.114328  , 6.41123866, 5.17721514, 3.8976963 , 3.65027836,
       2.94783879, 2.381553  ])

![](img/20.jpg)

In [ ]:
# Estimate the amount of clay
import numpy as np

n = 100000
V = 10 * 10 * 2
x = 10 * np.random.rand(n) - 5
y = 10 * np.random.rand(n) - 5
z = 2 * np.random.rand(n)

def check_in(x, y, z):
    if x**2 + y**2 < 25 and z > 0 and z < f(x,y):
        return 1
    return 0

n_in = np.sum(np.array([check_in(x[i], y[i], z[i]) for i in range(n)]))
volume = V * n_in/n